{
	"name": "ci",
	"on": {
		"push": {
			"branches": ["main"]
		}
	},
	"permissions": {
		"contents": "read",
		"pages": "write",
		"id-token": "write"
	},
	"jobs": {
		"build": {
			"runs-on": "ubuntu-latest",
			"steps": [
				{ "uses": "actions/checkout@v4", "with": { "ref": "main" } },
				{ "uses": "actions/setup-node@v4", "with": { "node-version": 20 } },
				{ "uses": "bahmutov/npm-install@v1", "with": { "useLockFile": false } },
				{ "run": "npm run build" },
				{
					"uses": "actions/upload-pages-artifact@v3",
					"with": {
						"path": "./docs"
					}
				}
			],
			"timeout-minutes": 15
		},
		"deploy": {
			"environment": {
				"name": "github-pages",
				"url": "${{ steps.deployment.outputs.page_url }}"
			},
			"runs-on": "ubuntu-latest",
			"needs": ["build"],
			"steps": [
				{
					"id": "deployment",
					"uses": "actions/deploy-pages@v4"
				}
			],
			"timeout-minutes": 15
		}
	}
}
